### ISSUE TITLE
 ROS 2 MCAP record Cache buffers lost messages per topic:

### ISSUE THREAD

**Issue by horverno** [jkk-research/docker_ros2_images#1]
``` py
 Cache buffers lost messages per topic: 
	/drone1/gps/duro/mag: 10
	/drone1/gps/duro/imu: 21
	/tf: 109
	/drone1/gps/duro/current_pose: 109
	/drone1/gps/duro/current_pose_with_cov: 109
	/drone1/os/imu: 2175
	/drone1/gps/duro/current_pose_fake_orientation: 109
	/drone1/os/range_image: 436
	/drone1/gps/duro/navsatfix: 109
	/drone1/os/reflec_image: 436
	/drone1/os/nearir_image: 436
	/drone1/os/signal_image: 436
	/drone1/os/points: 434
	/drone1/gps/duro/time_ref: 109
	/drone1/gps/duro/status_flag: 109
	/drone1/os/scan: 417
	/drone1/gps/duro/status_string: 109
	/drone1/gps/duro/odom: 109
Total lost: 5782

```

**Comment by horverno** [comment]
The solution is to use a similar command:

``` bash
ros2 bag record -s mcap --max-cache-size 1048576000 --storage-config-file $DIR1/mcap_writer_options1.yaml -a
```



[mcap_writer_options1.yaml](https://github.com/jkk-research/jkk_utils/blob/43ef7ee4c2d0eb95e6e0ff200d869cdf32e68d34/drone_bringup/etc/mcap_writer_options1.yaml)
``` yaml
 # mcap_writer_options1.yaml 
 noChunkCRC: false 
 noChunking: false 
 noMessageIndex: false 
 noSummary: false 
 chunkSize: 10485760 
 compression: "Zstd" 
 compressionLevel: "Fastest" 
 forceCompression: false 
```

example:
[record_mcap1.sh](https://github.com/jkk-research/jkk_utils/blob/ros2/drone_bringup/etc/record_mcap1.sh)
